name: draft1
description: UASD Mobile Application for Students
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  json_annotation: ^4.8.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.4+3
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
